
import type { OrderData, OrderStatus } from '../types';

export const orders: OrderData[] = [
  { orderId: '01011', date: '2025-01-21', customerName: 'Manish Verma', productName: 'Washing Machine', category: 'Electronics', quantity: 1, unitPrice: 25000, totalAmount: 25000, paymentMode: 'UPI' },
  { orderId: '01012', date: '2025-01-22', customerName: 'Ritu Singh', productName: 'Smartphone', category: 'Electronics', quantity: 2, unitPrice: 30000, totalAmount: 60000, paymentMode: 'Credit Card' },
  { orderId: '01013', date: '2025-01-23', customerName: 'Harish Gupta', productName: 'Microwave Oven', category: 'Electronics', quantity: 1, unitPrice: 12000, totalAmount: 12000, paymentMode: 'Cash' },
  { orderId: '01014', date: '2025-01-24', customerName: 'Anjali Nair', productName: 'Laptop', category: 'Electronics', quantity: 1, unitPrice: 55000, totalAmount: 55000, paymentMode: 'UPI' },
  { orderId: '01015', date: '2025-01-25', customerName: 'Deepak Bhosale', productName: 'Bluetooth Earbuds', category: 'Accessories', quantity: 3, unitPrice: 1800, totalAmount: 5400, paymentMode: 'Debit Card' },
  { orderId: '01016', date: '2025-01-26', customerName: 'Kavita Yadav', productName: 'Printer', category: 'Electronics', quantity: 1, unitPrice: 9000, totalAmount: 9000, paymentMode: 'UPI' },
  { orderId: '01017', date: '2025-01-27', customerName: 'Sanjay Pawar', productName: 'Camera', category: 'Electronics', quantity: 1, unitPrice: 32000, totalAmount: 32000, paymentMode: 'Credit Card' },
  { orderId: '01018', date: '2025-01-28', customerName: 'Meena Joshi', productName: 'Tablet', category: 'Electronics', quantity: 2, unitPrice: 18000, totalAmount: 36000, paymentMode: 'Cash' },
  { orderId: '01019', date: '2025-01-29', customerName: 'Ankit Patel', productName: 'Power Bank', category: 'Accessories', quantity: 4, unitPrice: 1200, totalAmount: 4800, paymentMode: 'UPI' },
  { orderId: '010110', date: '2025-01-30', customerName: 'Tina Fernandes', productName: 'Smart Watch', category: 'Accessories', quantity: 1, unitPrice: 7000, totalAmount: 7000, paymentMode: 'UPI' },
  { orderId: '010111', date: '2025-01-31', customerName: 'Ramesh Solanki', productName: 'Air Conditioner', category: 'Electronics', quantity: 1, unitPrice: 42000, totalAmount: 42000, paymentMode: 'Cash' },
  { orderId: '010112', date: '2025-02-01', customerName: 'Poonam Shinde', productName: 'LED TV', category: 'Electronics', quantity: 1, unitPrice: 36000, totalAmount: 36000, paymentMode: 'Credit Card' },
  { orderId: '010113', date: '2025-02-02', customerName: 'Shreya Nair', productName: 'Headphones', category: 'Accessories', quantity: 5, unitPrice: 1500, totalAmount: 7500, paymentMode: 'Debit Card' },
  { orderId: '010114', date: '2025-02-03', customerName: 'Vikas Jadhav', productName: 'Mobile Phone', category: 'Electronics', quantity: 1, unitPrice: 25000, totalAmount: 25000, paymentMode: 'UPI' },
  { orderId: '010115', date: '2025-02-04', customerName: 'Rachit Shah', productName: 'Refrigerator', category: 'Electronics', quantity: 1, unitPrice: 48000, totalAmount: 48000, paymentMode: 'UPI' },
  { orderId: '010116', date: '2025-02-05', customerName: 'Komal More', productName: 'Laptop', category: 'Electronics', quantity: 1, unitPrice: 55000, totalAmount: 55000, paymentMode: 'Cash' },
  { orderId: '010117', date: '2025-02-06', customerName: 'Swapnil Desai', productName: 'Bluetooth Speaker', category: 'Accessories', quantity: 2, unitPrice: 2000, totalAmount: 4000, paymentMode: 'Credit Card' },
  { orderId: '010118', date: '2025-02-07', customerName: 'Priyanka Rane', productName: 'Smart Watch', category: 'Accessories', quantity: 2, unitPrice: 7000, totalAmount: 14000, paymentMode: 'Debit Card' },
  { orderId: '010119', date: '2025-02-08', customerName: 'Jayesh Shinde', productName: 'Microwave Oven', category: 'Electronics', quantity: 1, unitPrice: 12000, totalAmount: 12000, paymentMode: 'UPI' },
  { orderId: '010120', date: '2025-02-09', customerName: 'Amrita Das', productName: 'Power Bank', category: 'Accessories', quantity: 3, unitPrice: 1200, totalAmount: 3600, paymentMode: 'Cash' },
  { orderId: '010121', date: '2025-02-09', customerName: 'Aryan Yadav', productName: 'Power Bank', category: 'Accessories', quantity: 3, unitPrice: 1200, totalAmount: 3600, paymentMode: 'Cash' },
];

export const statuses: OrderStatus[] = [
  { salesRep: 'Neha Joshi', status: 'Delivered', region: 'Mumbai', email: 'chandrikak@itm.edu', phone: '9324295820', verified: true, comment: '' },
  { salesRep: 'Arjun Mehta', status: 'Delivered', region: 'Pune', email: 'ritu.singh@gmail.com', phone: '9324295820', verified: true, comment: '' },
  { salesRep: 'Pooja Jain', status: 'Pending', region: 'Nashik', email: 'chandrikak@itm.edu', phone: '9324295820', verified: true, comment: '' },
  { salesRep: 'Neha Joshi', status: 'Delivered', region: 'Nagpur', email: 'chandrikak@itm.edu', phone: '9324295820', verified: true, comment: '' },
  { salesRep: 'Arjun Mehta', status: 'Cancelled', region: 'Thane', email: 'deepakb@gmail.com', phone: '9324295820', verified: true, comment: '' },
  { salesRep: 'Pooja Jain', 'status': 'Delivered', region: 'Mumbai', email: 'kavita.y@gmail.com', phone: '9324295820', verified: true, comment: '' },
  { salesRep: 'Neha Joshi', 'status': 'Delivered', region: 'Pune', email: 'sanjayp@gmail.com', phone: '9324295820', verified: 'N', comment: '' },
  { salesRep: 'Arjun Mehta', status: 'Pending', region: 'Nashik', email: 'meena.joshi@gmail.com', phone: '9324295820', verified: true, comment: '' },
  { salesRep: 'Pooja Jain', 'status': 'Delivered', region: 'Nagpur', email: 'ankitp@gmail.com', phone: '9324295820', verified: false, comment: 'khud aake lele' },
  { salesRep: 'Neha Joshi', 'status': 'Delivered', region: 'Mumbai', email: 'tinaf@gmail.com', phone: '9324295820', verified: 'N', comment: 'khud aake lele' },
  { salesRep: 'Arjun Mehta', status: 'Delivered', region: 'Thane', email: 'ramesh.s@gmail.com', phone: '9324295820', verified: true, comment: '' },
  { salesRep: 'Pooja Jain', 'status': 'Cancelled', region: 'Pune', email: 'poonam.shinde@gmail.com', phone: '9324295820', verified: true, comment: '' },
  { salesRep: 'Neha Joshi', 'status': 'Pending', region: 'Nashik', email: 'shreyan@gmail.com', phone: '9324295820', verified: true, comment: '' },
  { salesRep: 'Arjun Mehta', status: 'Delivered', region: 'Nagpur', email: 'vikasj@gmail.com', phone: '9324295820', verified: true, comment: '' },
  { salesRep: 'Pooja Jain', 'status': 'Delivered', region: 'Mumbai', email: 'rachit.shah@gmail.com', phone: '9324295820', verified: true, comment: '' },
  { salesRep: 'Neha Joshi', 'status': 'Delivered', region: 'Thane', email: 'komalm@gmail.com', phone: '9324295820', verified: true, comment: '' },
  { salesRep: 'Arjun Mehta', status: 'Pending', region: 'Pune', email: 'swapnild@gmail.com', phone: '9324295820', verified: true, comment: '' },
  { salesRep: 'Pooja Jain', 'status': 'Delivered', region: 'Nashik', email: 'priyankar@gmail.com', phone: '9324295820', verified: true, comment: '' },
  { salesRep: 'Neha Joshi', 'status': 'Delivered', region: 'Nagpur', email: 'jayeshs@gmail.com', phone: '9324295820', verified: true, comment: '' },
  { salesRep: 'Arjun Mehta', status: 'Cancelled', region: 'Mumbai', email: 'amritad@gmail.com', phone: '9324295820', verified: true, comment: '' },
  { salesRep: 'Arjun Mehta', status: 'Cancelled', region: 'Mumbai', email: 'amritad@gmail.com', phone: '9324295820', verified: true, comment: '' },
];
